source/InteropDemo.Web/Models/CourseViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace InteropDemo.Web.Models
{
    public class CourseViewModel
	{
		public int Id { get; set; }
		
		[Required]
		public string Title { get; set; }
		public string Description { get; set; }
		[Required]
		public string Room { get; set; }
		public double Investment { get; set; }
	}
}

source/InteropDemo.Web/Models/ErrorViewModel.cs
using System;

namespace InteropDemo.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

source/InteropDemo.Web/Models/StudentViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace InteropDemo.Web.Models
{
    public class StudentViewModel
    {
		public int Id { get; set; }
	    
		[Required]
		public string Name { get; set; }

	    [Required]
		[EmailAddress(ErrorMessage = "The Email field is invalid.")]
		public string Email { get; set; }
	    public string Phone { get; set; }
	    public int CourseId { get; set; }
	    public virtual CourseViewModel Course { get; set; }
	}
}

source/InteropDemo.Web/Controllers/CourseController.cs
using System.Linq;
using InteropDemo.Data.DataAccess;
using InteropDemo.Domain;
using InteropDemo.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace InteropDemo.Web.Controllers
{
	public class CourseController : Controller
	{
		private readonly IRepository<Course> _courseRepository;

		public CourseController(IRepository<Course> courseRepository)
		{
			this._courseRepository = courseRepository;
		}

		public ActionResult Index()
		{
			var coursesViewModel = _courseRepository.GetAll().Select(c=> new CourseViewModel
			{
				Id = c.Id,
				Title = c.Title,
				Description = c.Description,
				Investment = c.Investment,
				Room = c.Room
			});

			return View(coursesViewModel);
		}

		public ActionResult Create()
		{
			return View();
		}
		
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create(CourseViewModel courseViewModel)
		{
			try
			{
				if (!ModelState.IsValid)
					return View(courseViewModel);

				var courseDb = new Course
				{
					Title = courseViewModel.Title,
					Description = courseViewModel.Description,
					Investment = courseViewModel.Investment,
					Room = courseViewModel.Room
				};

				_courseRepository.Insert(courseDb);

				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View(courseViewModel);
			}
		}

		public ActionResult Edit(int id)
		{
			var courseDb = _courseRepository.Get(id);

			if (courseDb == null)
				return RedirectToAction(nameof(Index));

			var courseViewModel = new CourseViewModel
			{				
				Id = courseDb.Id,
				Title = courseDb.Title,
				Description = courseDb.Description,
				Investment = courseDb.Investment,
				Room = courseDb.Room
			};

			return View(courseViewModel);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(CourseViewModel courseViewModel)
		{
			try
			{
				if (!ModelState.IsValid)
					return View(courseViewModel);

				var courseDb = _courseRepository.Get(courseViewModel.Id);
				courseDb.Title = courseViewModel.Title;
				courseDb.Description = courseViewModel.Description;
				courseDb.Investment = courseViewModel.Investment;
				courseDb.Room = courseViewModel.Room;

				_courseRepository.Update(courseDb);

				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}
		
		public ActionResult Delete(int id)
		{
			var courseDb = _courseRepository.Get(id);

			if (courseDb != null)
				_courseRepository.Delete(courseDb);

			return RedirectToAction(nameof(Index));
		}
	}
}

source/InteropDemo.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using InteropDemo.Web.Models;

namespace InteropDemo.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

source/InteropDemo.Web/Controllers/StudentController.cs
using System.Linq;
using InteropDemo.Data.DataAccess;
using InteropDemo.Domain;
using InteropDemo.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace InteropDemo.Web.Controllers
{
	public class StudentController : Controller
	{
		private readonly IRepository<Student> _studentRepository;
		private readonly IRepository<Course> _courseRepository;

		public StudentController(IRepository<Student> studentRepository, IRepository<Course> courseRepository)
		{
			_studentRepository = studentRepository;
			_courseRepository = courseRepository;
		}

		public IActionResult Index()
		{
			var studentsViewModel = _studentRepository.GetAll().Select(s => new StudentViewModel
			{
				Id = s.Id,
				Name = s.Name,
				Email = s.Email,
				Phone = s.Phone,
				CourseId = s.CourseId
			}).ToList();

			foreach (var student in studentsViewModel)
			{
				var courseDb = _courseRepository.Get(student.CourseId);

				student.Course = new CourseViewModel
				{
					Id = courseDb.Id,
					Title = courseDb.Title,
					Description = courseDb.Description,
					Investment = courseDb.Investment,
					Room = courseDb.Room
				};
			}

			return View(studentsViewModel);
		}

		public ActionResult Create()
		{
			FillCourseList();

			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create(StudentViewModel studentViewModel)
		{
			try
			{
				if (!ModelState.IsValid)
					return View(studentViewModel);

				var studentDb = new Student
				{
					Id = studentViewModel.Id,
					Name = studentViewModel.Name,
					Email = studentViewModel.Email,
					Phone = studentViewModel.Phone,
					CourseId = studentViewModel.CourseId
				};

				_studentRepository.Insert(studentDb);

				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}

		public ActionResult Edit(int id)
		{
			var studentDb = _studentRepository.Get(id);

			if (studentDb == null)
				return RedirectToAction(nameof(Index));

			var studentViewModel = new StudentViewModel
			{
				Id = studentDb.Id,
				Name = studentDb.Name,
				Email = studentDb.Email,
				Phone = studentDb.Phone,
				CourseId = studentDb.CourseId
			};

			FillCourseList();

			return View(studentViewModel);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(StudentViewModel studentViewModel)
		{
			try
			{
				if (!ModelState.IsValid)
					return View(studentViewModel);

				var studentDb = _studentRepository.Get(studentViewModel.Id);
				studentDb.Name = studentViewModel.Name;
				studentDb.Phone = studentViewModel.Phone;
				studentDb.Email = studentViewModel.Email;
				studentDb.CourseId = studentViewModel.CourseId;

				_studentRepository.Update(studentDb);

				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}

		public ActionResult Delete(int id)
		{
			var studentDb = _studentRepository.Get(id);

			if (studentDb != null)
				_studentRepository.Delete(studentDb);

			return RedirectToAction(nameof(Index));
		}

		private void FillCourseList()
		{
			@ViewBag.CourseList = _courseRepository.GetAll().Select(c=> new CourseViewModel
			{
				Id = c.Id,
				Title = c.Title
			});
		}
	}
}

source/InteropDemo.Web/Views/Course/Create.cshtml
@model InteropDemo.Web.Models.CourseViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<h4>Course</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Room" class="control-label"></label>
                <input asp-for="Room" class="form-control" />
                <span asp-validation-for="Room" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Investment" class="control-label"></label>
                <input asp-for="Investment" class="form-control" />
                <span asp-validation-for="Investment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Cancel</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

source/InteropDemo.Web/Views/Course/Edit.cshtml
@model InteropDemo.Web.Models.CourseViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<h4>Course</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" disabled="disabled" readonly="readonly" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Room" class="control-label"></label>
                <input asp-for="Room" class="form-control" />
                <span asp-validation-for="Room" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Investment" class="control-label"></label>
                <input asp-for="Investment" class="form-control" />
                <span asp-validation-for="Investment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

source/InteropDemo.Web/Views/Course/Index.cshtml
@model IEnumerable<InteropDemo.Web.Models.CourseViewModel>

@{
    ViewData["Title"] = "Courses";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header">
	<h2>@ViewData["Title"]</h2>
</div>


<p>
	<a asp-action="Create" class="btn btn-default">
		<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
		Add
	</a>
</p>

<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Room)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Investment)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Room)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Investment)
            </td>
	        <td>		
		        @Html.ActionLink("Edit", "Edit", new { item.Id }, 
					new { @class = "btn btn-default" })
		        
				@Html.ActionLink("Delete", "Delete", new { item.Id },
					new {
						@onclick = "return confirm('Are you sure you want to delete this course?');",
						@class = "btn btn-default"
					})
	        </td>
        </tr>
}
    </tbody>
</table>

source/InteropDemo.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About Us";
}

<div class="page-header">
	<h2>@ViewData["Title"]</h2>
</div>

<div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-3 text-center">		
		<img class="img-circle img-responsive center-block" src="../images/marcel.jpg" alt="">
		<h3>Marcel Goldhardt
			<br/><small>Sr. Software Engineer</small>
		</h3>
		<h5>mail: <a href="mailto:marcel.goldhardt@dell.com">marcel.goldhardt@dell.com</a>  </h5>
		<p><i><strong>Mountains are calling and I must go </strong></i>
		</p>
	</div>
	<div class="col-md-2"></div>
	<div class="col-md-3 text-center">
		<img class="img-circle img-responsive center-block" src="../images/tiago.jpg" alt="">
		<h3>Tiago Moura
			<br /><small>Software Engineer</small>
		</h3>
		<h5>mail: <a href="mailto:tiago.gomes.moura@dell.com">tiago.gomes.moura@dell.com</a>  </h5>
		<p><i><strong>With great powers comes great responsability!</strong></i></p>
	</div>
	<div class="col-md-2"></div>
</div>

source/InteropDemo.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="page-header">
	<h1> @ViewData["Title"] </h1>
</div>

<div class="logos">
	<div class="row">
		<div class="col-md-4">
			<img src="images/interop_roadshow.png" alt="Dell Technologies" class="img-responsive center-block" />
		</div>
		<div class="col-md-4">
			<img src="images/ulbra.png" alt="Ulbra Canoas" class="img-responsive center-block" />
		</div>
		<div class="col-md-4">
			<img src="images/dell_technologies.jpg" alt="Dell Technologies" class="img-responsive center-block" />
		</div>
	</div>
</div>

source/InteropDemo.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Interop Demo</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
	<nav class="navbar navbar-inverse bg-primary container">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Interop Demo</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
	                <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
	                <li><a asp-area="" asp-controller="Course" asp-action="Index">Courses</a></li>
					<li><a asp-area="" asp-controller="Student" asp-action="Index">Students</a></li>
	                <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>                    
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()     
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

source/InteropDemo.Web/Views/Student/Create.cshtml
@model InteropDemo.Web.Models.StudentViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<h4>Student</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CourseId" class="control-label">Course</label>
	            <select asp-for="CourseId" class="form-control"
	                    asp-items="@(new SelectList(@ViewBag.CourseList, "Id", "Title", ""))"></select>
	            
				<span asp-validation-for="CourseId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

source/InteropDemo.Web/Views/Student/Edit.cshtml
@model InteropDemo.Web.Models.StudentViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<h4>Student</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" disabled="disabled" readonly="readonly"  />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CourseId" class="control-label"></label>

				<select asp-for="CourseId" class="form-control"
						asp-items="@(new SelectList(@ViewBag.CourseList, "Id", "Title", ""))"></select>
				

	            <span asp-validation-for="CourseId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

source/InteropDemo.Web/Views/Student/Index.cshtml
@model IEnumerable<InteropDemo.Web.Models.StudentViewModel>

@{
    ViewData["Title"] = "Students";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header">
	<h2>@ViewData["Title"]</h2>
</div>

<p>
	<a asp-action="Create" class="btn btn-default">
		<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
		Add
	</a>
</p>

<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Phone)
                </th>
                <th>
                    Course Title
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Course.Title)
            </td>
            <td>
	            @Html.ActionLink("Edit", "Edit", new { item.Id }, 
		            new { @class = "btn btn-default" })
		        
	            @Html.ActionLink("Delete", "Delete", new { item.Id },
		            new {
			            @onclick = "return confirm('Are you sure you want to delete this student?');",
			            @class = "btn btn-default"
		            })
            </td>
        </tr>
}
    </tbody>
</table>